/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.14
 * Generated at: 2022-01-26 01:36:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class MemberJoin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\"width:50%;margin:100px;auto;\">\r\n");
      out.write("<h2>회원가입</h2>\r\n");
      out.write("<form class=\"row g-3\" method=\"post\" action=\"/MemberJoin.do\" >\r\n");
      out.write("  <div class=\"col-md-6\">\r\n");
      out.write("    <label for=\"inputEmail4\" class=\"form-label\">Email</label>\r\n");
      out.write("    <input type=\"email\" class=\"form-control\" id=\"inputEmail4\" name=\"email\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-md-6\">\r\n");
      out.write("    <label for=\"inputPassword4\" class=\"form-label\">Password</label>\r\n");
      out.write("    <input type=\"password\" class=\"form-control\" id=\"inputPassword4\" name=\"pwd\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-12\">\r\n");
      out.write("    <label for=\"inputAddress\" class=\"form-label\">Address</label>\r\n");
      out.write("    <input type=\"text\" class=\"form-control\" id=\"inputAddress\" placeholder=\"1234 Main St\" name=\"addr1\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-12\">\r\n");
      out.write("    <label for=\"inputAddress2\" class=\"form-label\">Address 2</label>\r\n");
      out.write("    <input type=\"text\" class=\"form-control\" id=\"inputAddress2\" placeholder=\"Apartment, studio, or floor\" name=\"addr2\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-md-6\">\r\n");
      out.write("    <label for=\"inputCity\" class=\"form-label\">City</label>\r\n");
      out.write("    <input type=\"text\" class=\"form-control\" id=\"inputCity\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-md-4\">\r\n");
      out.write("    <label for=\"inputState\" class=\"form-label\">State</label>\r\n");
      out.write("    <select id=\"inputState\" class=\"form-select\">\r\n");
      out.write("      <option selected>Choose...</option>\r\n");
      out.write("      <option>...</option>\r\n");
      out.write("    </select>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-md-2\">\r\n");
      out.write("    <label for=\"inputZip\" class=\"form-label\">Zip</label>\r\n");
      out.write("    <input type=\"text\" class=\"form-control\" id=\"inputZip\" name=\"zipcode\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-12\">\r\n");
      out.write("    <div class=\"form-check\">\r\n");
      out.write("      <input class=\"form-check-input\" type=\"checkbox\" id=\"gridCheck\">\r\n");
      out.write("      <label class=\"form-check-label\" for=\"gridCheck\">\r\n");
      out.write("        Check me out\r\n");
      out.write("      </label>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-12\">\r\n");
      out.write("    <button type=\"submit\" class=\"btn btn-primary\">회원가입</button>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-12\">\r\n");
      out.write("    <a href=\"Login.jsp\" class=\"btn btn-primary\">이전으로</a>\r\n");
      out.write("  </div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
